name: flutter_mini_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  intl: ^0.19.0
  location: ^6.0.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
